USE [master]
GO
/****** Object:  Database [PARCIAL]    Script Date: 15/9/2025 19:31:14 ******/
CREATE DATABASE [PARCIAL]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PARCIAL', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\PARCIAL.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PARCIAL_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\PARCIAL_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [PARCIAL] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PARCIAL].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [PARCIAL] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [PARCIAL] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [PARCIAL] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [PARCIAL] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [PARCIAL] SET ARITHABORT OFF 
GO
ALTER DATABASE [PARCIAL] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [PARCIAL] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [PARCIAL] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [PARCIAL] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [PARCIAL] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [PARCIAL] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [PARCIAL] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [PARCIAL] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [PARCIAL] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [PARCIAL] SET  DISABLE_BROKER 
GO
ALTER DATABASE [PARCIAL] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [PARCIAL] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [PARCIAL] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [PARCIAL] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [PARCIAL] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [PARCIAL] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [PARCIAL] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [PARCIAL] SET RECOVERY FULL 
GO
ALTER DATABASE [PARCIAL] SET  MULTI_USER 
GO
ALTER DATABASE [PARCIAL] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [PARCIAL] SET DB_CHAINING OFF 
GO
ALTER DATABASE [PARCIAL] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [PARCIAL] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [PARCIAL] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [PARCIAL] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'PARCIAL', N'ON'
GO
ALTER DATABASE [PARCIAL] SET QUERY_STORE = ON
GO
ALTER DATABASE [PARCIAL] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [PARCIAL]
GO
/****** Object:  Table [dbo].[CLIENTE]    Script Date: 15/9/2025 19:31:14 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CLIENTE](
	[ID] [int] NOT NULL,
	[NOMBRE] [nvarchar](50) NOT NULL,
	[BORRADO] [int] NOT NULL,
 CONSTRAINT [PK_CLIENTE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[COMPRA]    Script Date: 15/9/2025 19:31:14 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[COMPRA](
	[ID_COMPRA] [int] NOT NULL,
	[ID_PRODUCTO] [int] NOT NULL,
	[ID_CLIENTE] [int] NOT NULL,
	[CANTIDAD] [int] NOT NULL,
 CONSTRAINT [PK_COMPRA] PRIMARY KEY CLUSTERED 
(
	[ID_COMPRA] ASC,
	[ID_PRODUCTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRODUCTO]    Script Date: 15/9/2025 19:31:14 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRODUCTO](
	[ID_PRODUCTO] [int] NOT NULL,
	[NOMBRE] [varchar](50) NOT NULL,
	[PRECIO] [float] NOT NULL,
 CONSTRAINT [PK_PRODUCTO] PRIMARY KEY CLUSTERED 
(
	[ID_PRODUCTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
INSERT [dbo].[PRODUCTO] ([ID_PRODUCTO], [NOMBRE], [PRECIO]) VALUES (1, N'LAPICERA', 1000)
GO
INSERT [dbo].[PRODUCTO] ([ID_PRODUCTO], [NOMBRE], [PRECIO]) VALUES (2, N'LAPIZ', 900)
GO
INSERT [dbo].[PRODUCTO] ([ID_PRODUCTO], [NOMBRE], [PRECIO]) VALUES (3, N'MARCADOR', 1500)
GO
ALTER TABLE [dbo].[COMPRA]  WITH CHECK ADD  CONSTRAINT [FK_COMPRA_CLIENTE] FOREIGN KEY([ID_CLIENTE])
REFERENCES [dbo].[CLIENTE] ([ID])
GO
ALTER TABLE [dbo].[COMPRA] CHECK CONSTRAINT [FK_COMPRA_CLIENTE]
GO
ALTER TABLE [dbo].[COMPRA]  WITH CHECK ADD  CONSTRAINT [FK_COMPRA_PRODUCTO] FOREIGN KEY([ID_PRODUCTO])
REFERENCES [dbo].[PRODUCTO] ([ID_PRODUCTO])
GO
ALTER TABLE [dbo].[COMPRA] CHECK CONSTRAINT [FK_COMPRA_PRODUCTO]
GO
USE [master]
GO
ALTER DATABASE [PARCIAL] SET  READ_WRITE 
GO
